apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: FRONTEND_URL
              value: "http://localhost:31823"
            - name: NODE_ENV
              value: "development"

            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_CONNECTION_STRING

            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: ACCESS_TOKEN_SECRET

            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REFRESH_TOKEN_SECRET

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GOOGLE_CLIENT_SECRET

            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SESSION_SECRET

            - name: GNEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GNEWS_API_KEY